version: "3"

services:
  slides:
    image: slides
    build: ./slides
    ports:
      - 31337:80/tcp
    networks:
      outside:

  vpnconfig:
    image: nginx:latest
    ports:
      - 31338:80/tcp
    volumes:
      - wireguard_configs:/etc/nginx/html/
      - ./vpnconfig_templates:/etc/nginx/templates
    environment:
      - NGINX_HOST=localhost:31338
      - NGINX_PORT=80
    networks:
      outside:

  chal0:
    image: chal0
    build: 
      context: ./chal0
    ports:
      - 80/tcp
    volumes:
      - ./chal0/nginx_templates:/etc/nginx/templates
    environment:
      - NGINX_HOST=172.28.1.2
      - NGINX_PORT=80
    networks:
      internal:
        ipv4_address: 172.28.1.2

  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=101
      - PGID=101
      - TZ=Europe/Berlin
      - SERVERURL=10.151.5.231
      - SERVERPORT=51820
      - PEERS=200
      - PEERDNS=1.1.1.1
      - INTERNAL_SUBNET=172.28.2.0
      - ALLOWEDIPS=172.28.1.0/24
    volumes:
      - wireguard_configs:/config
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    networks:
      outside:
      internal:
        ipv4_address: 172.28.1.1

volumes:
  wireguard_configs:


networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1
  outside:
