version: "3"

services:
  slides:
    image: slides
    build: ./slides
    ports:
      - 31337:80/tcp
    networks:
      outside:

  vpnconfig:
    image: nginx:latest
    ports:
      - 31338:80/tcp
    volumes:
      - wireguard_configs:/etc/nginx/html/
      - ./vpnconfig_templates:/etc/nginx/templates
    environment:
      - NGINX_HOST=localhost:31338
      - NGINX_PORT=80
    networks:
      outside:

  chal0:
    image: chal0
    restart: unless-stopped
    build: 
      context: ./chal0
    ports:
      - 80/tcp
    volumes:
      - ./chal0/nginx_templates:/etc/nginx/templates
    environment:
      - NGINX_HOST=172.28.1.3
      - NGINX_PORT=80
    networks:
      internal:
        ipv4_address: 172.28.1.3


  chal1:
    image: chal1
    restart: unless-stopped
    build: 
      context: ./chal1
    cap_add:
      - NET_ADMIN
    ports:
      - 1337/tcp
    environment:
      - PEER_SUBNET=172.28.2.0/24
      - PEER_GATEWAY=172.28.1.2
    networks:
      internal:
        ipv4_address: 172.28.1.4

  chal2:
    image: chal2
    build:
      context: ./chal2/keyserver
    ports:
      - 80/tcp
    volumes:
      - ./chal2/user_key:/opt/static/user_key:ro
    networks:
      internal:
        ipv4_address: 172.28.1.5
    restart: unless-stopped

  chal2b:
    image: lscr.io/linuxserver/openssh-server:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PUBLIC_KEY_FILE=/user_key.pub
      - USER_NAME=admin
    volumes:
      - ./chal2/user_key.pub:/user_key.pub
      - ./chal2/controlserver/network_daemon.sh:/custom-services.d/network_daemon.sh:ro
    ports:
      - 2222/tcp
    restart: unless-stopped
    networks:
      non_reachable:
        ipv4_address: 172.28.3.3
      internal:
        ipv4_address: 172.28.1.6


  chal2c:
    image: chal2c
    build:
      context: ./chal2/answerserver
    ports:
      - 80/tcp
    networks:
      non_reachable:
        ipv4_address: 172.28.3.2
    restart: unless-stopped

  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=101
      - PGID=101
      - TZ=Europe/Berlin
      - SERVERURL=10.151.5.231
      - SERVERPORT=51820
      - PEERS=200
      - PEERDNS=1.1.1.1
      - INTERNAL_SUBNET=172.28.2.0/24
      - ALLOWEDIPS=172.28.1.0/24
    volumes:
      - wireguard_configs:/config
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: unless-stopped
    networks:
      outside:
      internal:
        ipv4_address: 172.28.1.2

volumes:
  wireguard_configs:


networks:
  internal:
    #internal: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.1.0/24
          gateway: 172.28.1.1
  
  non_reachable:
    #internal: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.3.0/24
          gateway: 172.28.3.1
  outside:
